#management endpoints on a separate port
server:
  port: 8081

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

  # ===============================
  # = Mysql configurations
  # ===============================
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring_project?useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true&useSSL=false
    username: mysql
    password: mysql

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    root: WARN
    com.jeonguk.web: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE